version: "3.9"

services:
  postgres:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: customer_db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  mock-server:
    build: ./mock-server
    ports:
      - "5000:5000"

  pipeline-service:
    build: ./pipeline-service
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
      mock-server:
        condition: service_started
    environment:
      # SQLAlchemy DB URL
      DATABASE_URL: postgresql://postgres:password@postgres:5432/customer_db

      # dlt credentials (VERY IMPORTANT)
      DESTINATION__POSTGRES__CREDENTIALS__DATABASE: customer_db
      DESTINATION__POSTGRES__CREDENTIALS__USERNAME: postgres
      DESTINATION__POSTGRES__CREDENTIALS__PASSWORD: password
      DESTINATION__POSTGRES__CREDENTIALS__HOST: postgres
      DESTINATION__POSTGRES__CREDENTIALS__PORT: 5432
